src/Entity/Invoice.php
<?php

namespace App\Entity;

use App\Repository\InvoiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InvoiceRepository::class)
 */
class Invoice
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $number;

    /**
     * @ORM\Column(type="date")
     */
    private $invoicing_date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $invoicing_place;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $sale_date;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $seller_nip;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $seller_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true))
     */
    private $seller_street;

    /**
     * @ORM\Column(type="string", length=255, nullable=true))
     */
    private $seller_postal_code;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $seller_city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $seller_account_bank_number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $seller_bank;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $buyer_type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $buyer_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true))
     */
    private $buyer_nip;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $buyer_street;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $buyer_postal_code;

    /**
     * @ORM\Column(type="string", length=255, nullable=true))
     */
    private $buyer_city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true))
     */
    private $payment_period;

    /**
     * @ORM\Column(type="string", length=255, nullable=true))
     */
    private $status;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=0, nullable=true))
     */
    private $amount_paid;

    /**
     * @ORM\Column(type="string", length=255, nullable=true))
     */
    private $invoice_issuer;

    /**
     * @ORM\Column(type="string", length=255, nullable=true))
     */
    private $invoice_recipient;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $currency;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2, nullable=true))
     */
    private $netto_sum;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2, nullable=true))
     */
    private $vat_sum;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2, nullable=true))
     */
    private $brutto_sum;

    /**
     * @ORM\OneToMany(targetEntity=InvoiceItem::class, mappedBy="invoice", orphanRemoval=true, cascade={"persist"})
     */
    private $items;

    public function __construct()
    {
        $this->items = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(string $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getInvoicingDate(): ?\DateTimeInterface
    {
        return $this->invoicing_date;
    }

    public function setInvoicingDate(\DateTimeInterface $invoicing_date): self
    {
        $this->invoicing_date = $invoicing_date;

        return $this;
    }

    public function getInvoicingPlace(): ?string
    {
        return $this->invoicing_place;
    }

    public function setInvoicingPlace(string $invoicing_place): self
    {
        $this->invoicing_place = $invoicing_place;

        return $this;
    }

    public function getSaleDate(): ?\DateTimeInterface
    {
        return $this->sale_date;
    }

    public function setSaleDate(?\DateTimeInterface $sale_date): self
    {
        $this->sale_date = $sale_date;

        return $this;
    }

    public function getSellerNip(): ?string
    {
        return $this->seller_nip;
    }

    public function setSellerNip(string $seller_nip): self
    {
        $this->seller_nip = $seller_nip;

        return $this;
    }

    public function getSellerName(): ?string
    {
        return $this->seller_name;
    }

    public function setSellerName(string $seller_name): self
    {
        $this->seller_name = $seller_name;

        return $this;
    }

    public function getSellerPostalCode(): ?string
    {
        return $this->seller_postal_code;
    }

    public function setSellerPostalCode(string $seller_postal_code): self
    {
        $this->seller_postal_code = $seller_postal_code;

        return $this;
    }

    public function getSellerCity(): ?string
    {
        return $this->seller_city;
    }

    public function setSellerCity(string $seller_city): self
    {
        $this->seller_city = $seller_city;

        return $this;
    }

    public function getSellerAccountBankNumber(): ?string
    {
        return $this->seller_account_bank_number;
    }

    public function setSellerAccountBankNumber(string $seller_account_bank_number): self
    {
        $this->seller_account_bank_number = $seller_account_bank_number;

        return $this;
    }

    public function getSellerBank(): ?string
    {
        return $this->seller_bank;
    }

    public function setSellerBank(string $seller_bank): self
    {
        $this->seller_bank = $seller_bank;

        return $this;
    }

    public function getBuyerType(): ?string
    {
        return $this->buyer_type;
    }

    public function setBuyerType(string $buyer_type): self
    {
        $this->buyer_type = $buyer_type;

        return $this;
    }

    public function getBuyerName(): ?string
    {
        return $this->buyer_name;
    }

    public function setBuyerName(string $buyer_name): self
    {
        $this->buyer_name = $buyer_name;

        return $this;
    }

    public function getBuyerStreet(): ?string
    {
        return $this->buyer_street;
    }

    public function setBuyerStreet(string $buyer_street): self
    {
        $this->buyer_street = $buyer_street;

        return $this;
    }

    public function getBuyerPostalCode(): ?string
    {
        return $this->buyer_postal_code;
    }

    public function setBuyerPostalCode(string $buyer_postal_code): self
    {
        $this->buyer_postal_code = $buyer_postal_code;

        return $this;
    }

    public function getBuyerCity(): ?string
    {
        return $this->buyer_city;
    }

    public function setBuyerCity(string $buyer_city): self
    {
        $this->buyer_city = $buyer_city;

        return $this;
    }

    public function getPaymentPeriod(): ?string
    {
        return $this->payment_period;
    }

    public function setPaymentPeriod(string $payment_period): self
    {
        $this->payment_period = $payment_period;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getAmountPaid(): ?string
    {
        return $this->amount_paid;
    }

    public function setAmountPaid(string $amount_paid): self
    {
        $this->amount_paid = $amount_paid;

        return $this;
    }

    public function getInvoiceIssuer(): ?string
    {
        return $this->invoice_issuer;
    }

    public function setInvoiceIssuer(string $invoice_issuer): self
    {
        $this->invoice_issuer = $invoice_issuer;

        return $this;
    }

    public function getInvoiceRecipient(): ?string
    {
        return $this->invoice_recipient;
    }

    public function setInvoiceRecipient(string $invoice_recipient): self
    {
        $this->invoice_recipient = $invoice_recipient;

        return $this;
    }

    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    public function setCurrency(string $currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    public function getNettoSum(): ?string
    {
        return $this->netto_sum;
    }

    public function setNettoSum(string $netto_sum): self
    {
        $this->netto_sum = $netto_sum;

        return $this;
    }

    public function getVatSum(): ?string
    {
        return $this->vat_sum;
    }

    public function setVatSum(string $vat_sum): self
    {
        $this->vat_sum = $vat_sum;

        return $this;
    }

    public function getBruttoSum(): ?string
    {
        return $this->brutto_sum;
    }

    public function setBruttoSum(string $brutto_sum): self
    {
        $this->brutto_sum = $brutto_sum;

        return $this;
    }

    /**
     * @return Collection|InvoiceItem[]
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(InvoiceItem $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items[] = $item;
            $item->setInvoice($this);
        }

        return $this;
    }

    public function removeItem(InvoiceItem $item): self
    {
        if ($this->items->contains($item)) {
            $this->items->removeElement($item);

src/Controller/InvoiceController.php
<?php

namespace App\Controller;

use App\Entity\Invoice;
use App\Entity\InvoiceItem;
use App\Form\InvoiceType;
use App\Repository\InvoiceRepository;
use App\Service\InvoiceService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/invoice")
 */
class InvoiceController extends AbstractController
{
    private $is;

    public function __construct(InvoiceService $is)
    {
        $this->is = $is;
    }

    /**
     * @Route("/", name="invoice_index", methods={"GET"})
     */
    public function index(InvoiceRepository $invoiceRepository): Response
    {
        return $this->render('invoice/index.html.twig', [
            'invoices' => $invoiceRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="invoice_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $invoice = new Invoice();
        $invoice->setNumber($this->is->generateNumber());
        $form = $this->createForm(InvoiceType::class, $invoice);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($invoice);
            $entityManager->flush();

            return $this->redirectToRoute('invoice_index');
        }

        return $this->render('invoice/new.html.twig', [
            'invoice' => $invoice,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="invoice_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Invoice $invoice): Response
    {
        $form = $this->createForm(InvoiceType::class, $invoice);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('invoice_index');
        }

        return $this->render('invoice/edit.html.twig', [
            'invoice' => $invoice,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="invoice_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Invoice $invoice): Response
    {
        if ($this->isCsrfTokenValid('delete' . $invoice->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($invoice);
            $entityManager->flush();
        }

        return $this->redirectToRoute('invoice_index');
    }
}

templates/invoice/_delete_form.html.twig
<form method="post" action="{{ path('invoice_delete', {'id': invoice.id}) }}"
      onsubmit="return confirm('Jesteś pewny usunięcia tego elementu?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ invoice.id) }}">
    <button class="btn btn-danger">Usuń</button>
</form>

templates/invoice/_form.html.twig
{{ form_start(form) }}
<div class="my-custom-class-for-errors">
    {{ form_errors(form) }}
</div>

<div class="row mt-4">
    <div class="col">
        {{ form_row(form.type) }}
    </div>
    <div class="col">
        {{ form_row(form.number) }}
    </div>
    <div class="col" id="some-custom-id">
        {{ form_row(form.invoicing_date) }}
    </div>
    <div class="col" id="some-custom-id">
        {{ form_row(form.invoicing_place) }}
    </div>
    <div class="col" id="some-custom-id">
        {{ form_row(form.sale_date) }}
    </div>
</div>
<hr/>
<div class="row">
    <div class="col">
        <h3>Sprzedawca</h3>
        <div class="row">
            <div class="col">
                {{ form_row(form.seller_name) }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form_row(form.seller_nip) }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form_row(form.seller_street) }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form_row(form.seller_postal_code) }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form_row(form.seller_city) }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form_row(form.seller_account_bank_number) }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form_row(form.seller_bank) }}
            </div>
        </div>
    </div>
    <div class="col">
        <h3>Nabywca</h3>
        <div class="row">
            <div class="col">
                {{ form_row(form.buyer_type) }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form_row(form.buyer_name) }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form_row(form.buyer_nip) }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form_row(form.buyer_street) }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form_row(form.buyer_postal_code) }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form_row(form.buyer_city) }}
            </div>
        </div>
    </div>
</div>
<hr/>
<h3>Pozycje</h3>
<table class="table table-hover items"
       data-prototype="
        <tr>
            <td width='30%'>{{ form_row(form.items.vars.prototype.name)|e }}</td>
            <td width='10%'>{{ form_row(form.items.vars.prototype.amount)|e }}</td>
            <td width='10%'>{{ form_row(form.items.vars.prototype.unit)|e }}</td>
            <td width='10%'>{{ form_row(form.items.vars.prototype.vat)|e }}</td>
            <td width='15%'>{{ form_row(form.items.vars.prototype.price_netto)|e }}</td>
            <td width='15%'>{{ form_row(form.items.vars.prototype.price_brutto)|e }}</td>
            <td width='10%'><button class='btn btn-danger delete'>Usuń</button></td>
        </tr>"
>
    <tr>
        <th width='30%'>Nazwa</th>
        <th width='10%'>Ilość</th>
        <th width='10%'>Jedn.</th>
        <th width='10%'>VAT</th>
        <th width='15%'>Netto</th>
        <th width='15%'>Brutto</th>
        <th width='10%' class="add_option"></th>
    </tr>
    {% for item in form.items %}
        <tr>
            <td width='30%'>{{ form_row(item.name) }}</td>
            <td width='10%'>{{ form_row(item.amount) }}</td>
            <td width='10%'>{{ form_row(item.unit) }}</td>
            <td width='10%'>{{ form_row(item.vat) }}</td>
            <td width='15%'>{{ form_row(item.price_netto) }}</td>
            <td width='15%'>{{ form_row(item.price_brutto) }}</td>
            <td width='10%'>
                <button class='btn btn-danger delete'>Usuń</button>
            </td>
        </tr>
    {% endfor %}
</table>
<div class="row ">
    <div class="col-3 offset-9">
        {{ form_row(form.netto_sum) }}
    </div>
</div>
<div class="row">
    <div class="col-3 offset-9">
        {{ form_row(form.vat_sum) }}
    </div>
</div>
<div class="row">
    <div class="col-3 offset-9">
        {{ form_row(form.brutto_sum) }}
    </div>
</div>

<hr/>
<div class="row">
    <div class="col">
        {{ form_row(form.status) }}
    </div>
    <div class="col">
        {{ form_row(form.amount_paid) }}
    </div>
</div>
<hr/>
<div class="row">
    <div class="col">
        {{ form_row(form.invoice_issuer) }}
    </div>
    <div class="col">
        {{ form_row(form.invoice_recipient) }}
    </div>
</div>
<div class="row">
    <div class="col">
        {{ form_row(form.currency) }}
    </div>
</div>
<button class="btn btn-success">{{ button_label|default('Zapisz') }}</button>
{{ form_end(form) }}
<script>
    function addItemForm($collectionHolder, $newLinkLi) {
        var prototype = $collectionHolder.data('prototype');
        var index = $collectionHolder.data('index');

        var newForm = prototype;
        newForm = newForm.replace(/__name__/g, index);
        $collectionHolder.data('index', index + 1);

        $('table.items tbody').append(newForm);
    }

    function recalculationSums() {

        var netto_sum = 0;
        $('.price_netto').each(function () {
            var amount = parseInt($(this).closest('tr').find('.amount').val());
            netto_sum += parseFloat($(this).val()) * amount;  // Or this.innerHTML, this.innerText
        });
        $('.netto_sum').val(netto_sum.toFixed(2));

        var brutto_sum = 0;
        $('.price_brutto').each(function () {
            var amount = parseInt($(this).closest('tr').find('.amount').val());
            brutto_sum += parseFloat($(this).val()) * amount;  // Or this.innerHTML, this.innerText
        });
        $('.brutto_sum').val(brutto_sum.toFixed(2));

        var vat_sum = brutto_sum - netto_sum;
        $('.vat_sum').val(vat_sum.toFixed(2));

    }

    // setup an "add a tag" link
    var $addTagButton = $('<button type="button" class="btn btn-success add_button">Dodaj</button>');
    var $newLinkLi = $('<tr></tr>');

    jQuery(document).ready(function () {

        $(document).on('change', '.amount', function () {
            recalculationSums();
        });
        $(document).on('change', '.price_netto', function () {
            var priceNetto = parseFloat($(this).val());
            var vat = parseInt($(this).closest('tr').find('.vat').val());
            var priceBrutto = priceNetto * (1 + (vat / 100));
            if (vat) {
                $(this).parent().closest('tr').find('.price_brutto').val(priceBrutto.toFixed(2));
            } else {
                $(this).parent().closest('tr').find('.price_brutto').val(priceNetto.toFixed(2));
            }
            recalculationSums();
        });
        $(document).on('change', '.price_brutto', function () {
            var priceBrutto = parseFloat($(this).val());
            var vat = parseInt($(this).closest('tr').find('.vat').val());
            var priceNetto = priceBrutto / (1 + (vat / 100));
            if (vat) {
                $(this).parent().closest('tr').find('.price_netto').val(priceNetto.toFixed(2));
            } else {
                $(this).parent().closest('tr').find('.price_netto').val(priceBrutto.toFixed(2));
            }
            recalculationSums();
        });
        $(document).on('change', '.vat', function () {
            var vat = parseInt($(this).closest('tr').find('.vat').val());
            $(this).parent().closest('tr').find('.price_netto').change();
            recalculationSums();
        });

        $collectionHolder = $('table.items');
        $('.add_option').append($addTagButton);
        $collectionHolder.data('index', $collectionHolder.find('input').length);

        $addTagButton.on('click', function (e) {
            // add a new tag form (see next code block)
            addItemForm($collectionHolder, $newLinkLi);
        });
        $collectionHolder.on("click", ".delete", function () {
            $(this).closest("tr").remove();
        });
    });
</script>

templates/invoice/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edycja faktury{% endblock %}

{% block body %}
    <h1 class="mt-4">Edycja faktury</h1>

    <a class="btn btn-primary" href="{{ path('invoice_index') }}">Powrót</a>

    {{ include('invoice/_form.html.twig', {'button_label': 'Zapisz'}) }}

    {{ include('invoice/_delete_form.html.twig') }}
{% endblock %}

templates/invoice/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lista faktur{% endblock %}

{% block body %}
    <h1 class="mt-4">Lista faktur</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Numer</th>
            <th>Typ</th>
            <th>Data wystawienia</th>
            <th>Data sprzedaży</th>
            <th>Klient</th>
            <th>Netto</th>
            <th>Brutto</th>
            <th>Status</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for invoice in invoices %}
            <tr>
                <td>{{ invoice.number }}</td>
                <td>{{ invoice.type }}</td>
                <td>{{ invoice.invoicingDate ? invoice.invoicingDate|date('Y-m-d') : '' }}</td>
                <td>{{ invoice.saleDate ? invoice.invoicingDate|date('Y-m-d') : '' }}</td>
                <td>{{ invoice.buyerName }}</td>
                <td>{{ invoice.nettoSum }}</td>
                <td>{{ invoice.bruttoSum }}</td>
                <td>{{ invoice.status }}</td>
                <td>
                    <a class="btn btn-success" href="{{ path('invoice_edit', {'id': invoice.id}) }}">Edycja</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="27">Nie odnaleziono rekordów</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-success" href="{{ path('invoice_new') }}">Utwórz</a>
{% endblock %}

templates/invoice/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utworzenie faktury{% endblock %}

{% block body %}
    <h1 class="mt-4">Utworzenie faktury</h1><br/>

    <a class="btn btn-primary" href="{{ path('invoice_index') }}">Powrót</a>

    {{ include('invoice/_form.html.twig') }}

{% endblock %}